buildscript {
    repositories {
        maven {
            url 'http://localhost:8080/snapshots'
        }

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'

        classpath 'info.gianlucacosta.moondeploy:moondeploy-gradle:4.0.0-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'application'
}

apply plugin: 'info.gianlucacosta.moondeploy'
apply plugin: 'info.gianlucacosta.aurora'

group 'info.gianlucacosta.historymark'
archivesBaseName = 'historymark'
version '2.0.0-SNAPSHOT'

sourceCompatibility = 1.8

description = 'Interactive Java app for historical events'

mainClassName = 'info.gianlucacosta.historymark.App'

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    javaVersion {
        major = 11
        minor = 0
        build = 0
        update = 0
    }
}

dependencies {
    compile 'info.gianlucacosta.atlas:atlas:2.0.0-SNAPSHOT'
    compile 'info.gianlucacosta.zephyros:zephyros-core:2.0.0-SNAPSHOT'
    compile 'info.gianlucacosta.zephyros:zephyros-hibernate:2.0.0-SNAPSHOT'

    compile 'org.hsqldb:hsqldb:2.4.0'
    compile 'com.thoughtworks.xstream:xstream:1.4.10'

    compile 'javax.xml.bind:jaxb-api:2.3.1'
    compile 'com.sun.xml.bind:jaxb-core:2.3.0.1'
    compile 'com.sun.xml.bind:jaxb-impl:2.3.2'

    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
}
